# Generated by Django 4.2.5 on 2023-10-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0002_product_pimage_alter_product_cat_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seed',
            field=models.IntegerField(choices=[(1, 'HORTICULTURE'), (2, 'FILED CROP'), (3, 'Special CAREGORIES')], default=0, verbose_name='cat seed'),
            preserve_default=False,
        ),
    ]
