# Generated by Django 4.2.5 on 2023-10-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0003_product_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seed',
            field=models.IntegerField(choices=[(1, 'HORTICULTURE'), (2, 'FILED CROP'), (3, 'Special CAREGORIES'), (4, 'None')], verbose_name='cat seed'),
        ),
    ]
