# Generated by Django 4.2.5 on 2023-10-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0007_alter_cart_pid_alter_cart_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
